version: "3.7"

services:
  portal:
    container_name: ast-nginx-portal
    image: ast_nginx:latest
    hostname: ast-nginx-portal
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/tomcat-cluster.conf:/etc/nginx/conf.d/tomcat-cluster.conf
    networks:
      - ast_tomcat_cluster

  tomcat1:
    container_name: ast-tomcat1
    image: ast_tomcat:latest
    hostname: ast-tomcat1
    restart: always
    ports:
      - 8881:8080
    volumes:
      - ./tomcat/server.xml:/usr/local/tomcat/conf/server.xml
      - ./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      # - ./tomcat/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    networks:
      - ast_tomcat_cluster

  tomcat2:
    container_name: ast-tomcat2
    image: ast_tomcat:latest
    hostname: ast-tomcat2
    restart: always
    ports:
      - 8882:8080
    volumes:
      - ./tomcat/server.xml:/usr/local/tomcat/conf/server.xml
      - ./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      # - ./tomcat/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml
      - ./tomcat/webapps:/usr/local/tomcat/webapps
    networks:
      - ast_tomcat_cluster

networks:
  ast_tomcat_cluster:
    driver: bridge
